In [1]:
import re
from pathlib import Path
import warnings
import os

import numpy as np
import pandas as pd
from nptdms import TdmsFile
import subprocess

from tqdm.auto import tqdm

warnings.filterwarnings("ignore")

/home/evs/Desktop/venv/ML_venv/lib/python3.6/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
tdms_dir = Path(r"../SAS_data")
tdms_list = []

for root, dirs, files in os.walk(tdms_dir):
    for file in files:
        if file.endswith(".tdms"):
            tdms_list.append(os.path.join(root, file))

In [3]:
vaild_file = [
     'k1_vernier_1_1.tdms',
 'k1_vernier_1_2.tdms',
 'k1_vernier_1_3.tdms',
 'k1_vernier_1_4.tdms',
 'k1_vernier_1_5.tdms',

 'k1_vernier_2__1.tdms',
 'k1_vernier_2__2.tdms',
 'k1_vernier_2__3.tdms',
 'k1_vernier_2__4.tdms',
 'k1_vernier_2__5.tdms',

 'k1_vernier_0_1.tdms',
 'k1_vernier_0_2.tdms',
 'k1_vernier_0_3.tdms',
 'k1_vernier_0_4.tdms',
 'k1_vernier_0_5.tdms',



 'k2_vernier_0__1.tdms',
 'k2_vernier_0__2.tdms',
 'k2_vernier_0__3.tdms',
 'k2_vernier_0__4.tdms',
 'k2_vernier_0__5.tdms',

 'k2_vernier_1__1.tdms',
 'k2_vernier_1__2.tdms',
 'k2_vernier_1__3.tdms',
 'k2_vernier_1__4.tdms',
 'k2_vernier_1__5.tdms',

 'k2_vernier_2__1.tdms',
 'k2_vernier_2__2.tdms',
 'k2_vernier_2__3.tdms',
 'k2_vernier_2__4.tdms',
 'k2_vernier_2__5.tdms',



 'k3_vernier_0__1.tdms',
 'k3_vernier_0__2.tdms',
 'k3_vernier_0__3.tdms',
 'k3_vernier_0__4.tdms',
 'k3_vernier_0__5.tdms',

 'k3_vernier_1__1.tdms',
 'k3_vernier_1__2.tdms',
 'k3_vernier_1__3.tdms',
 'k3_vernier_1__4.tdms',
 'k3_vernier_1__5.tdms',

 'k3_vernier_2__1.tdms',
 'k3_vernier_2__2.tdms',
 'k3_vernier_2__3.tdms',
 'k3_vernier_2__4.tdms',
 'k3_vernier_2__5.tdms',



 'k4_vernier_0__1.tdms',
 'k4_vernier_0__2.tdms',
 'k4_vernier_0__3.tdms',
 'k4_vernier_0__4.tdms',
 'k4_vernier_0__5.tdms',

 'k4_vernier_1__1.tdms',
 'k4_vernier_1__2.tdms',
 'k4_vernier_1__3.tdms',
 'k4_vernier_1__4.tdms',
 'k4_vernier_1__5.tdms',

 'k4_vernier_2__1.tdms',
 'k4_vernier_2__2.tdms',
 'k4_vernier_2__3.tdms',
 'k4_vernier_2__4.tdms',
 'k4_vernier_2__5.tdms',



 'k5_vernier_0__1.tdms',
 'k5_vernier_0__2.tdms',
 'k5_vernier_0__3.tdms',
 'k5_vernier_0__4.tdms',
 'k5_vernier_0__5.tdms',

 'k5_vernier_1__1.tdms',
 'k5_vernier_1__2.tdms',
 'k5_vernier_1__3.tdms',
 'k5_vernier_1__4.tdms',
 'k5_vernier_1__5.tdms',

 'k5_vernier_2__1.tdms',
 'k5_vernier_2__2.tdms',
 'k5_vernier_2__3.tdms',
 'k5_vernier_2__4.tdms',
 'k5_vernier_2__5.tdms'
]

In [4]:
filterd_list = [(f, f.split("/")[-1]) for f in tdms_list if 'vernier' in f.lower()]

# filterd_list = [f for f in filterd_list if 'k1' in f]

filterd_list = [f[0] for f in filterd_list if f[1] in vaild_file]

filterd_list

['../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k5_vernier_1__4.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k2_vernier_1__4.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k3_vernier_2__5.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k3_vernier_1__4.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k5_vernier_0__2.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k5_vernier_1__1.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k2_vernier_0__5.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k1_vernier_0_2.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k3_vernier_2__4.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k5_vernier_0__4.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k3_vernier_1__2.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k2_vernier_0__2.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k2_vernier_2__3.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k3_vernier_0__3.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k3_vernier_2__3.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k1_vernier_1_4.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k4_vernier_1__5.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k2_vernier_2__5.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k1_vernier_1_5.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k5_vernier_1__2.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k1_vernier_0_3.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k2_vernier_0__1.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k1_vernier_2__5.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k1_vernier_0_1.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k3_vernier_0__4.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k5_vernier_1__5.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k2_vernier_0__4.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k4_vernier_0__3.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k4_vernier_2__4.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k2_vernier_1__3.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k2_vernier_1__1.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k2_vernier_2__2.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k1_vernier_0_5.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k1_vernier_1_3.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k3_vernier_0__1.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k1_vernier_1_2.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k1_vernier_2__1.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k4_vernier_1__3.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k2_vernier_2__1.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k5_vernier_2__2.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k4_vernier_0__1.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k3_vernier_2__1.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k5_vernier_1__3.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k2_vernier_2__4.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k3_vernier_0__5.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k3_vernier_1__3.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k3_vernier_1__5.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k1_vernier_2__3.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k1_vernier_0_4.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k4_vernier_2__3.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k4_vernier_0__2.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k4_vernier_2__2.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k5_vernier_0__1.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k1_vernier_1_1.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k3_vernier_2__2.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k5_vernier_2__4.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k4_vernier_2__1.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k2_vernier_1__5.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k5_vernier_2__1.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k5_vernier_2__5.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k4_vernier_0__5.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k2_vernier_0__3.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k4_vernier_0__4.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k4_vernier_1__1.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k3_vernier_1__1.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k3_vernier_0__2.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k5_vernier_0__3.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k5_vernier_0__5.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k5_vernier_2__3.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k4_vernier_2__5.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k4_vernier_1__4.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k1_vernier_2__4.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k2_vernier_1__2.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k4_vernier_1__2.tdms',
 '../SAS_data/26022026wieliczka-20260331T135931Z-3-001/26022026wieliczka/k1_vernier_2__2.tdms']

In [5]:
data_list = []

for tdms_file_path in filterd_list:
    file_name = tdms_file_path.split("/")[-1].replace('__', '_')
    file_name = file_name.replace('.tdms', '').split('_')
    file_name = ''.join([file_name[0], '_', file_name[2], '_', file_name[3]])
    
    tdms_file = TdmsFile.read(tdms_file_path)
    
    for group in tdms_file.groups():
        for channel in group.channels():
            data_len = np.shape(channel.data)[0]
            if (file_name[0] != 'z' and channel.name == 'Voltage'):
                data_list.append({
                    'excitation': channel.data,
                    'identifier': file_name  
                })
    print(file_name)

k5_1_4
k2_1_4
k3_2_5
k3_1_4
k5_0_2
k5_1_1
k2_0_5
k1_0_2
k3_2_4
k5_0_4
k3_1_2
k2_0_2
k2_2_3
k3_0_3
k3_2_3
k1_1_4
k4_1_5
k2_2_5
k1_1_5
k5_1_2
k1_0_3
k2_0_1
k1_2_5
k1_0_1
k3_0_4
k5_1_5
k2_0_4
k4_0_3
k4_2_4
k2_1_3
k2_1_1
k2_2_2
k1_0_5
k1_1_3
k3_0_1
k1_1_2
k1_2_1
k4_1_3
k2_2_1
k5_2_2
k4_0_1
k3_2_1
k5_1_3
k2_2_4
k3_0_5
k3_1_3
k3_1_5
k1_2_3
k1_0_4
k4_2_3
k4_0_2
k4_2_2
k5_0_1
k1_1_1
k3_2_2
k5_2_4
k4_2_1
k2_1_5
k5_2_1
k5_2_5
k4_0_5
k2_0_3
k4_0_4
k4_1_1
k3_1_1
k3_0_2
k5_0_3
k5_0_5
k5_2_3
k4_2_5
k4_1_4
k1_2_4
k2_1_2
k4_1_2
k1_2_2

In [6]:
df_magnitude = pd.DataFrame(data_list)

In [7]:
df_magnitude['len'] = df_magnitude['excitation'].apply(len)

df_magnitude['excitation'] = df_magnitude['excitation'].apply(lambda x: x[50000:100000])
df_magnitude['len'] = df_magnitude['excitation'].apply(len)

In [8]:
df_magnitude = df_magnitude.drop(['len'], axis=1)

df_magnitude

                                           excitation identifier
0   [4.359465196, 5.376966602, 4.72265357, 2.34678...     k5_1_4
1   [1.233302932, 10.320983932, 10.465749096, 6.98...     k2_1_4
2   [1.84488792, -4.956204994, -5.811403606, -5.83...     k3_2_5
3   [-4.721838484, 2.323505786, 5.346674332, 5.354...     k3_1_4
4   [6.879144328000001, 5.653104558, 2.3327529, -2...     k5_0_2
..                                                ...        ...
70  [-4.284354332, -3.72410677, -3.978561838, -1.2...     k4_1_4
71  [3.4672781280000002, 4.520492526, 1.41282449, ...     k1_2_4
72  [-5.333742338, -10.431134214, -10.257033378000...     k2_1_2
73  [0.117590798, -5.46192647, -5.397834404, -5.33...     k4_1_2
74  [-0.815092252, -4.082512154, -3.748659452, 0.0...     k1_2_2

[75 rows x 2 columns]

In [9]:
def group_help(x: str) -> str:
    x = x.split('_')
    
    return ''.join([x[0], '_', x[2]])
    

df_magnitude['identifier'] = df_magnitude['identifier'].apply((lambda x: group_help(x)))

In [10]:
#def stack_signal(x: list) -> np.array:
    

df_magnitude = df_magnitude.groupby('identifier').apply(lambda x: np.stack(x['excitation']))

In [11]:
df_magnitude = pd.DataFrame(df_magnitude)

In [12]:
df_magnitude = df_magnitude.reset_index()
df_magnitude.columns = "id", 'signals'

In [13]:
tmp_folder = r'../tmp'
program_path = r'../build/CUDA'
paths = [r'../tmp/sig_0.txt', r'../tmp/sig_1.txt', r'../tmp/sig_2.txt']

# Upewnij się, że folder istnieje
os.makedirs(tmp_folder, exist_ok=True)

results = []

for row_idx, row in tqdm(df_magnitude.iterrows(), total=df_magnitude.shape[0]):
    signals = row['signals']

    for sig_idx in range(3):
        sig_data = np.array(signals[sig_idx])
        np.savetxt(paths[sig_idx], sig_data, fmt='%.6f')
    
    # 2. Odpalamy proces (teraz mamy pewność, że pliki istnieją i są 3)
    try:
        process = subprocess.run(
            [program_path, paths[0], paths[1], paths[2]],
            stdout=subprocess.PIPE,  # Zamiennik capture_output=True
            stderr=subprocess.PIPE,  # Zamiennik capture_output=True
            universal_newlines=True, # Zamiennik text=True w Pythonie 3.6
            check=True
        )

        # Wynik odbierasz tak samo
        prediction = process.stdout.strip()
        print(prediction)
        results.append(prediction)

    except subprocess.CalledProcessError as e:
        print(f"Błąd w wierszu {row_idx}: {e.stderr}")
        results.append("ERROR")

# 3. Na koniec dodaj wyniki do nowej kolumny
df_magnitude['prediction'] = results

  4%|▍         | 1/25 [00:51<20:39, 51.65s/it]

TensorRT engine loaded, output size: 2
0 -2.52148
0.925634 0.0743657

  8%|▊         | 2/25 [01:19<14:23, 37.53s/it]

TensorRT engine loaded, output size: 2
0 -2.52148
0.925634 0.0743657

 12%|█▏        | 3/25 [01:45<11:53, 32.45s/it]

TensorRT engine loaded, output size: 2
0 -2.52148
0.925634 0.0743657

 16%|█▌        | 4/25 [02:15<10:59, 31.42s/it]

TensorRT engine loaded, output size: 2
-2 -2.51953
0.627038 0.372962

 20%|██        | 5/25 [02:46<10:25, 31.27s/it]

TensorRT engine loaded, output size: 2
-512 -2.51953
0 1

 24%|██▍       | 6/25 [03:17<09:52, 31.17s/it]

TensorRT engine loaded, output size: 2
0 -2.52148
0.925634 0.0743657

 28%|██▊       | 7/25 [03:48<09:17, 30.95s/it]

TensorRT engine loaded, output size: 2
0 -2.52148
0.925634 0.0743657

 32%|███▏      | 8/25 [04:17<08:38, 30.49s/it]

TensorRT engine loaded, output size: 2
-512 -2.51953
0 1

 36%|███▌      | 9/25 [04:45<07:53, 29.59s/it]

TensorRT engine loaded, output size: 2
0 -2.52148
0.925634 0.0743657

 40%|████      | 10/25 [05:17<07:37, 30.50s/it]

TensorRT engine loaded, output size: 2
0 -2.52148
0.925634 0.0743657

 44%|████▍     | 11/25 [05:48<07:08, 30.62s/it]

TensorRT engine loaded, output size: 2
-2 -2.51953
0.627038 0.372962

 48%|████▊     | 12/25 [06:15<06:24, 29.61s/it]

TensorRT engine loaded, output size: 2
-0.0078125 -2.51953
0.924959 0.0750407

 52%|█████▏    | 13/25 [06:44<05:51, 29.32s/it]

TensorRT engine loaded, output size: 2
-0.0078125 -2.51953
0.924959 0.0750407

 56%|█████▌    | 14/25 [07:09<05:08, 28.07s/it]

TensorRT engine loaded, output size: 2
-0.0078125 -2.51953
0.924959 0.0750407

 60%|██████    | 15/25 [07:41<04:53, 29.31s/it]

TensorRT engine loaded, output size: 2
0 -2.52148
0.925634 0.0743657

 64%|██████▍   | 16/25 [08:11<04:23, 29.32s/it]

TensorRT engine loaded, output size: 2
-0.0078125 -2.51953
0.924959 0.0750407

 68%|██████▊   | 17/25 [08:37<03:47, 28.44s/it]

TensorRT engine loaded, output size: 2
-0.0078125 -2.51953
0.924959 0.0750407

 72%|███████▏  | 18/25 [09:06<03:20, 28.62s/it]

TensorRT engine loaded, output size: 2
-2 -2.51953
0.627038 0.372962

 76%|███████▌  | 19/25 [09:35<02:51, 28.56s/it]

TensorRT engine loaded, output size: 2
-512 -2.51953
0 1

 80%|████████  | 20/25 [10:07<02:28, 29.72s/it]

TensorRT engine loaded, output size: 2
-512 -2.51953
0 1

 84%|████████▍ | 21/25 [10:32<01:53, 28.26s/it]

TensorRT engine loaded, output size: 2
-2 -2.51953
0.627038 0.372962

 88%|████████▊ | 22/25 [10:57<01:22, 27.46s/it]

TensorRT engine loaded, output size: 2
-512 -2.51953
0 1

 92%|█████████▏| 23/25 [11:26<00:55, 27.79s/it]

TensorRT engine loaded, output size: 2
-2 -2.51953
0.627038 0.372962

 96%|█████████▌| 24/25 [11:56<00:28, 28.43s/it]

TensorRT engine loaded, output size: 2
-2 -2.51953
0.627038 0.372962

100%|██████████| 25/25 [12:22<00:00, 29.70s/it]

TensorRT engine loaded, output size: 2
-2 -2.51953
0.627038 0.372962

In [16]:
df_magnitude['prediction'] = df_magnitude['prediction'].apply(lambda x: x.split('\n')[-1])

df_magnitude['prediction'] = df_magnitude['prediction'].apply(lambda x: x.split())

AttributeError: 'list' object has no attribute 'split'

In [17]:
df_magnitude

,id,signals,prediction
0,k1_1,"[[-9.499407762, -10.431134214, -10.431134214, ...","[0.925634, 0.0743657]"
1,k1_2,"[[-10.431134214, -7.991490448, -1.508944668, 5...","[0.925634, 0.0743657]"
2,k1_3,"[[-1.9470665520000001, -7.796982188, -10.43113...","[0.925634, 0.0743657]"
3,k1_4,"[[2.8757816980000004, 6.1007924220000005, 3.62...","[0.627038, 0.372962]"
4,k1_5,"[[2.5913532260000003, 0.81335641, 4.192379412,...","[0, 1]"
5,k2_1,"[[-5.183875318, 1.325455206, 5.816045084000001...","[0.925634, 0.0743657]"
6,k2_2,"[[-7.7752993, -3.420865204, 3.142991406, 7.776...","[0.925634, 0.0743657]"
7,k2_3,"[[2.96091892, 4.14391178, 2.4842142500000004, ...","[0, 1]"
8,k2_4,"[[1.233302932, 10.320983932, 10.465749096, 6.9...","[0.925634, 0.0743657]"
9,k2_5,"[[2.466357754, -4.210058554, -9.450302398, -9....","[0.925634, 0.0743657]"
10,k3_1,"[[6.966832478000001, 0.590469076, -5.93703681,...","[0.627038, 0.372962]"
11,k3_2,"[[-6.162793938, -6.172678784, -6.062032282, 1....","[0.924959, 0.0750407]"
12,k3_3,"[[3.6793240180000004, -0.626004714, -4.8203680...","[0.924959, 0.0750407]"
13,k3_4,"[[-4.721838484, 2.323505786, 5.346674332, 5.35...","[0.924959, 0.0750407]"
14,k3_5,"[[1.84488792, -4.956204994, -5.811403606, -5.8...","[0.925634, 0.0743657]"
15,k4_1,"[[2.5741344620000004, -5.564920188, -10.200275...","[0.924959, 0.0750407]"
16,k4_2,"[[-2.126269244, 5.876629624, 6.000349632, 0.30...","[0.924959, 0.0750407]"
17,k4_3,"[[3.700369174, -3.96166194, -5.837231752, -1.6...","[0.627038, 0.372962]"
18,k4_4,"[[6.435920588, 7.2560439400000005, 5.102422976...","[0, 1]"
19,k4_5,"[[-3.425648194, -8.009346944, -10.181781002, -...","[0, 1]"
20,k5_1,"[[5.14036803, 3.618739478, 0.855446722, -2.090...","[0.627038, 0.372962]"
21,k5_2,"[[6.879144328000001, 5.653104558, 2.3327529, -...","[0, 1]"
22,k5_3,"[[-3.9862146220000003, -1.1530902120000002, 1....","[0.627038, 0.372962]"
23,k5_4,"[[4.359465196, 5.376966602, 4.72265357, 2.3467...","[0.627038, 0.372962]"
24,k5_5,"[[2.67872251, 4.782919244, 5.419694646, 4.1544...","[0.627038, 0.372962]"

In [18]:
df_magnitude['class'] = df_magnitude['prediction'].apply(lambda x: np.argmax(x))

In [19]:
1 - df_magnitude['class'].sum()/len(df_magnitude['class'])

0.8

In [24]:
df_magnitude.drop(['true_class'], axis=1)

,id,signals,prediction,class
0,k1_1,"[[-9.499407762, -10.431134214, -10.431134214, ...","[0.925634, 0.0743657]",0
1,k1_2,"[[-10.431134214, -7.991490448, -1.508944668, 5...","[0.925634, 0.0743657]",0
2,k1_3,"[[-1.9470665520000001, -7.796982188, -10.43113...","[0.925634, 0.0743657]",0
3,k1_4,"[[2.8757816980000004, 6.1007924220000005, 3.62...","[0.627038, 0.372962]",0
4,k1_5,"[[2.5913532260000003, 0.81335641, 4.192379412,...","[0, 1]",1
5,k2_1,"[[-5.183875318, 1.325455206, 5.816045084000001...","[0.925634, 0.0743657]",0
6,k2_2,"[[-7.7752993, -3.420865204, 3.142991406, 7.776...","[0.925634, 0.0743657]",0
7,k2_3,"[[2.96091892, 4.14391178, 2.4842142500000004, ...","[0, 1]",1
8,k2_4,"[[1.233302932, 10.320983932, 10.465749096, 6.9...","[0.925634, 0.0743657]",0
9,k2_5,"[[2.466357754, -4.210058554, -9.450302398, -9....","[0.925634, 0.0743657]",0
10,k3_1,"[[6.966832478000001, 0.590469076, -5.93703681,...","[0.627038, 0.372962]",0
11,k3_2,"[[-6.162793938, -6.172678784, -6.062032282, 1....","[0.924959, 0.0750407]",0
12,k3_3,"[[3.6793240180000004, -0.626004714, -4.8203680...","[0.924959, 0.0750407]",0
13,k3_4,"[[-4.721838484, 2.323505786, 5.346674332, 5.35...","[0.924959, 0.0750407]",0
14,k3_5,"[[1.84488792, -4.956204994, -5.811403606, -5.8...","[0.925634, 0.0743657]",0
15,k4_1,"[[2.5741344620000004, -5.564920188, -10.200275...","[0.924959, 0.0750407]",0
16,k4_2,"[[-2.126269244, 5.876629624, 6.000349632, 0.30...","[0.924959, 0.0750407]",0
17,k4_3,"[[3.700369174, -3.96166194, -5.837231752, -1.6...","[0.627038, 0.372962]",0
18,k4_4,"[[6.435920588, 7.2560439400000005, 5.102422976...","[0, 1]",1
19,k4_5,"[[-3.425648194, -8.009346944, -10.181781002, -...","[0, 1]",1
20,k5_1,"[[5.14036803, 3.618739478, 0.855446722, -2.090...","[0.627038, 0.372962]",0
21,k5_2,"[[6.879144328000001, 5.653104558, 2.3327529, -...","[0, 1]",1
22,k5_3,"[[-3.9862146220000003, -1.1530902120000002, 1....","[0.627038, 0.372962]",0
23,k5_4,"[[4.359465196, 5.376966602, 4.72265357, 2.3467...","[0.627038, 0.372962]",0
24,k5_5,"[[2.67872251, 4.782919244, 5.419694646, 4.1544...","[0.627038, 0.372962]",0

In [22]:
df_magnitude

,id,signals,prediction,class,true_class
0,k1_1,"[[-9.499407762, -10.431134214, -10.431134214, ...","[0.925634, 0.0743657]",0,0
1,k1_2,"[[-10.431134214, -7.991490448, -1.508944668, 5...","[0.925634, 0.0743657]",0,0
2,k1_3,"[[-1.9470665520000001, -7.796982188, -10.43113...","[0.925634, 0.0743657]",0,0
3,k1_4,"[[2.8757816980000004, 6.1007924220000005, 3.62...","[0.627038, 0.372962]",0,0
4,k1_5,"[[2.5913532260000003, 0.81335641, 4.192379412,...","[0, 1]",1,0
5,k2_1,"[[-5.183875318, 1.325455206, 5.816045084000001...","[0.925634, 0.0743657]",0,0
6,k2_2,"[[-7.7752993, -3.420865204, 3.142991406, 7.776...","[0.925634, 0.0743657]",0,0
7,k2_3,"[[2.96091892, 4.14391178, 2.4842142500000004, ...","[0, 1]",1,0
8,k2_4,"[[1.233302932, 10.320983932, 10.465749096, 6.9...","[0.925634, 0.0743657]",0,0
9,k2_5,"[[2.466357754, -4.210058554, -9.450302398, -9....","[0.925634, 0.0743657]",0,0
10,k3_1,"[[6.966832478000001, 0.590469076, -5.93703681,...","[0.627038, 0.372962]",0,0
11,k3_2,"[[-6.162793938, -6.172678784, -6.062032282, 1....","[0.924959, 0.0750407]",0,0
12,k3_3,"[[3.6793240180000004, -0.626004714, -4.8203680...","[0.924959, 0.0750407]",0,0
13,k3_4,"[[-4.721838484, 2.323505786, 5.346674332, 5.35...","[0.924959, 0.0750407]",0,0
14,k3_5,"[[1.84488792, -4.956204994, -5.811403606, -5.8...","[0.925634, 0.0743657]",0,0
15,k4_1,"[[2.5741344620000004, -5.564920188, -10.200275...","[0.924959, 0.0750407]",0,0
16,k4_2,"[[-2.126269244, 5.876629624, 6.000349632, 0.30...","[0.924959, 0.0750407]",0,0
17,k4_3,"[[3.700369174, -3.96166194, -5.837231752, -1.6...","[0.627038, 0.372962]",0,0
18,k4_4,"[[6.435920588, 7.2560439400000005, 5.102422976...","[0, 1]",1,0
19,k4_5,"[[-3.425648194, -8.009346944, -10.181781002, -...","[0, 1]",1,0
20,k5_1,"[[5.14036803, 3.618739478, 0.855446722, -2.090...","[0.627038, 0.372962]",0,0
21,k5_2,"[[6.879144328000001, 5.653104558, 2.3327529, -...","[0, 1]",1,0
22,k5_3,"[[-3.9862146220000003, -1.1530902120000002, 1....","[0.627038, 0.372962]",0,0
23,k5_4,"[[4.359465196, 5.376966602, 4.72265357, 2.3467...","[0.627038, 0.372962]",0,0
24,k5_5,"[[2.67872251, 4.782919244, 5.419694646, 4.1544...","[0.627038, 0.372962]",0,0